### ISSUE TITLE
[META] Decommission the Doomscrolling Study: Oct 13

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-study-01#125]
The Doomscrolling study is scheduled to end on October 13. We need to shut it down and rescind access to it.

- [x] [Pause data collection](https://github.com/mozilla-rally/study-remote-settings/issues/14)
- [x] Remove the ability to enroll
  - [x] [from the Rally website](https://github.com/mozilla-rally/site/issues/427)
- [ ] [Update extension with final messaging and uninstall mechanism](https://github.com/mozilla-rally/rally-study-01/issues/128)
- [x] Landing Page
  - [x] [Messaging](https://github.com/mozilla-rally/rally-study-01/issues/129)
  - [x] [Build page](https://github.com/mozilla-rally/site/issues/429)
- [x] [Remove from AMO](https://github.com/mozilla-rally/rally-study-01/issues/130)

There are other post decommission tasks that will be captured in separate issues, namely conduct analysis and decommission analysis environment and pipeline
