### ISSUE TITLE
[META] Decommission the Princeton Core Add-on based study 12/14/2021

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-study-01#134]
The Princeton study is scheduled to end on December 14. We need to shut it down and rescind access to it.

- [ ] Pause data collection
- [ ]  Remove the ability to enroll
  - [ ] from the Rally website
- [ ] Update extension with final messaging and uninstall mechanism
- [ ] Landing Page
  - [ ]  Messaging
   - [ ] Build page
- [ ] Remove from AMO
