### ISSUE TITLE
[meta] RS01 Checkpoint 10 remaining Engineering Deliverables

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-study-01#24]
Filing this as a cycle-length meta issue.

- [x] integrate `rally.js` #27 
- [x] change event names #15 
- [x] reorganize local storage to be keyed by page id #23 
- [x] clean up rollup scripts & output
- [x] reintegrate / clean up pre-existing unit tests #36
- [x] configure this study to actually send data via rally.js #33
- [x] fix lint issues #32
