### ISSUE TITLE
[meta] RS01 Checkpoint 11 Engineering Deliverables

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-study-01#35]
The main objective for Checkpoint 11 Engineering: get this study web extension reviewed by the addons team. Here is a priority-ordered list of engineering tasks:

## Needed for data alignment worksheet review
- [x] align actual web extension schema to data alignment worksheet #55 
- [x] measurements schema #7 
- [x] validate all measurements #42 
- [x] get initial engineering review on the schema & match against data alignment worksheet: does the data schema match the proposal? mozilla-rally/internal#57
- [x] implement the data minimization captured in #76 –– *WIP #75*

## Needed to ship the study web extension
- [x] integrate study id and JWK token into code #40
- [x] get full data alignment review from engineering: does this collection actually match the proposal? mozilla-rally/internal#69
- [x] update `manifest.json` with a short study description and the right icon #62 –– *WIP #77*
- [x] fix bundling issue by moving the `attention-collector.js` to the `dist` directory via rollup #79
- [x] Rally team code review of the study extension mozilla-rally/internal#58
- [x] notify the add-ons team that we will need a review #58
- [x] pause collection if study receives killswitch message #59
- [x] develop a first-pass QA plan #34
- [x] set up CI on this repository #16 
- [x] remove inspector + options page #60 
- [x] submit to AMO

## Needed for table creation / deployment
- [x] Ops submission requirements (#57)
